Repository CovidTrackerFr/vitemadose-ios, pull requests merged in 2021-12, with the labels that each got.

#141 🐛 Fixed wrong twitter account link in settings
  ViteMaDose/Views/Settings/SettingsViewController.swift
Labels: bug

#158 fix: #155 - label text size for followed centers cell
  ViteMaDose/Views/Home/Cells/HomeFollowedCentresCell.swift
Labels: bug

#159 #142 - Third dose
  ViteMaDose.xcodeproj/project.pbxproj
  ViteMaDose.xcodeproj/xcshareddata/xcschemes/Debug.xcscheme
  ViteMaDose.xcodeproj/xcshareddata/xcschemes/Release.xcscheme
  ViteMaDose.xcodeproj/xcshareddata/xcschemes/ViteMaDoseTests.xcscheme
  ViteMaDose/Helpers/Extensions/Bool+Commons.swift
  ViteMaDose/Helpers/Utils/AppAnalytics.swift
  ViteMaDose/Helpers/Utils/OnboardingManager.swift
  ViteMaDose/Models/DailySlot.swift
  ViteMaDose/Models/DepartmentSlots.swift
  ViteMaDose/Models/VaccinationCentre.swift
  ViteMaDose/Networking/BaseAPIService.swift
  ViteMaDose/Networking/RemoteConfig.swift
  ViteMaDose/Resources/Localization/Localization.swift
  ViteMaDose/Resources/Localization/fr.lproj/Localizable.strings
  ViteMaDose/ViewModels/CentresList/CentresListSortOption.swift
  ViteMaDose/ViewModels/CentresList/CentresListViewModel.swift
  ViteMaDose/ViewModels/FollowedCentres/FollowedCentresViewModel.swift
  ViteMaDose/Views/CentresList/Cells/CentreCell.xib
  ViteMaDose/Views/CentresList/Cells/CentresSortOptionsCell.swift
  ViteMaDose/Views/Home/Footer/HomePartnersFooterView.swift
  ViteMaDose/Views/Home/HomeViewController.swift
  ViteMaDose/remote-configuration.plist
Labels: enhancement

#165 Update tags management for kids shot to avoid app bug
  ViteMaDose/Models/DailySlot.swift
Labels: bug, high priority

#103 ✨ Fix MaPharma time
  ViteMaDose/Helpers/Extensions/String+Commons.swift
Labels: bug, high priority
