Repository CovidTrackerFr/vitemadose-ios, pull requests merged in 2021-11, with the labels that each got.

#137 ✨ Updating dependencies to fix warnings
  ViteMaDose.xcodeproj/project.pbxproj
  ViteMaDose.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: high priority

#133 💄 Bimedoc logo support
  ViteMaDose/Models/PartnerLogo.swift
  ViteMaDose/Resources/Assets.xcassets/Images/bimedoc.imageset/Contents.json
  ViteMaDose/Resources/Assets.xcassets/Images/bimedoc.imageset/logo-e21915b3.svg
  ViteMaDose/ViewModels/CentresList/CentresListViewModel.swift
  ViteMaDose/Views/Home/Footer/HomePartnersFooterView.swift
  ViteMaDose/Views/Home/Footer/HomePartnersFooterView.xib
Labels: UI

#135 Text size in followed centers cell follows A11Y rules
  ViteMaDose/Views/Home/Cells/HomeFollowedCentresCell.swift
Labels: bug

#123 Settings screen
  ViteMaDose.xcodeproj/project.pbxproj
  ViteMaDose/Helpers/Extensions/UIFont+TextSizes.swift
  ViteMaDose/Resources/Localization/Localization.swift
  ViteMaDose/Resources/Localization/fr.lproj/Localizable.strings
  ViteMaDose/Views/Home/Cells/HomeTitleCell.swift
  ViteMaDose/Views/Home/HomeViewController.storyboard
  ViteMaDose/Views/Home/HomeViewController.swift
  ViteMaDose/Views/Settings/Cells/SettingsCell.swift
  ViteMaDose/Views/Settings/Cells/SettingsCell.xib
  ViteMaDose/Views/Settings/Cells/SettingsTitleCell.swift
  ViteMaDose/Views/Settings/Cells/SettingsTitleCell.xib
  ViteMaDose/Views/Settings/SettingsViewController.storyboard
  ViteMaDose/Views/Settings/SettingsViewController.swift
Labels: UI

#139 🐛 Fixed Bimedoc logo not showing up
  ViteMaDose/Resources/Assets.xcassets/Images/bimedoc.imageset/Bimedoc.pdf
  ViteMaDose/Resources/Assets.xcassets/Images/bimedoc.imageset/Contents.json
  ViteMaDose/Resources/Assets.xcassets/Images/bimedoc.imageset/logo-e21915b3.svg
Labels: bug
