Repository CovidTrackerFr/vitemadose-ios, pull requests merged in 2021-04, with the labels that each got.

#16 Fix - Project scheme is missing
  ViteMaDose.xcodeproj/xcshareddata/xcschemes/ViteMaDose.xcscheme
Labels: bug, high priority

#17 Department Selection - Reduce spacing between cells
  ViteMaDose/Views/CountySelection/Cells/CountyCellTableViewCell.xib
  ViteMaDose/Views/CountySelection/Header/CountySelectionHeaderView.swift
  ViteMaDose/Views/CountySelection/Header/CountySelectionHeaderView.xib
Labels: UI

#6 Feature - Vaccination centres list
  ViteMaDose.xcodeproj/project.pbxproj
  ViteMaDose.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ViteMaDose/Helpers/Extensions/Data+Commons.swift
  ViteMaDose/Helpers/Extensions/NSMutableAttributedString+Commons.swift
  ViteMaDose/Helpers/Extensions/NSTextAttachment+Commons.swift
  ViteMaDose/Helpers/Extensions/URL+Commons.swift
  ViteMaDose/Info.plist
  ViteMaDose/Models/PartnerLogo.swift
  ViteMaDose/Models/VaccinationCentre.swift
  ViteMaDose/Networking/APIEndpoint.swift
  ViteMaDose/Resources/Assets.xcassets/Colors/royalBlue.colorset/Contents.json
  ViteMaDose/Resources/Assets.xcassets/Images/Doctolib.imageset/Contents.json
  ViteMaDose/Resources/Assets.xcassets/Images/Doctolib.imageset/doctolib-logo.pdf
  ViteMaDose/Resources/Assets.xcassets/Images/Keldoc.imageset/Contents.json
  ViteMaDose/Resources/Assets.xcassets/Images/Keldoc.imageset/keldoc-logo.pdf
  ViteMaDose/Resources/Assets.xcassets/Images/Maiia.imageset/Contents.json
  ViteMaDose/Resources/Assets.xcassets/Images/Maiia.imageset/maiia.pdf
  ViteMaDose/Resources/Assets.xcassets/Images/Mapharma.imageset/Contents.json
  ViteMaDose/Resources/Assets.xcassets/Images/Mapharma.imageset/mapharma-logo.pdf
  ViteMaDose/Resources/Assets.xcassets/Images/Ordoclic.imageset/Contents.json
  ViteMaDose/Resources/Assets.xcassets/Images/Ordoclic.imageset/ordoclic.pdf
  ViteMaDose/Resources/Assets.xcassets/Images/logo.imageset/logo-dark.pdf
  ViteMaDose/Resources/Assets.xcassets/Images/logo.imageset/logo.pdf
  ViteMaDose/ViewModels/Home/HomeViewModel.swift
  ViteMaDose/ViewModels/VaccinationCentres/VaccinationCentresViewModel.swift
  ViteMaDose/Views/Home/Cells/HomePartnersTableViewCell.swift
  ViteMaDose/Views/Home/Cells/HomePartnersTableViewCell.xib
  ViteMaDose/Views/Home/Cells/HomeStatsTableViewCell.swift
  ViteMaDose/Views/Home/Cells/HomeStatsTableViewCell.xib
  ViteMaDose/Views/Home/HomeViewController.swift
  ViteMaDose/Views/VaccinationCentres/Cells/VaccinationBookingTableViewCell.swift
  ViteMaDose/Views/VaccinationCentres/Cells/VaccinationBookingTableViewCell.xib
  ViteMaDose/Views/VaccinationCentres/Header/VaccinationCentresHeaderView.swift
  ViteMaDose/Views/VaccinationCentres/Header/VaccinationCentresHeaderView.xib
  ViteMaDose/Views/VaccinationCentres/VaccinationCentresViewController.storyboard
  ViteMaDose/Views/VaccinationCentres/VaccinationCentresViewController.swift
Labels: dependent, enhancement

#9 Introduce Firebase RemoteConfig, Crashlytics and Analytics
  ViteMaDose.xcodeproj/project.pbxproj
  ViteMaDose.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ViteMaDose.xcodeproj/xcshareddata/xcschemes/Debug.xcscheme
  ViteMaDose.xcodeproj/xcshareddata/xcschemes/Release.xcscheme
  ViteMaDose/AppDelegate.swift
  ViteMaDose/GoogleService-Info.plist
  ViteMaDose/Helpers/Utils/AppAnalytics.swift
  ViteMaDose/Info.plist
  ViteMaDose/Networking/APIEndpoint.swift
  ViteMaDose/Networking/RemoteConfig.swift
  ViteMaDose/SceneDelegate.swift
  ViteMaDose/ViewModels/VaccinationCentres/VaccinationCentresViewModel.swift
  ViteMaDose/Views/Home/HomeViewController.swift
  ViteMaDose/remote-configuration.plist
Labels: enhancement

#21 Fix archive upload error
  ViteMaDose.xcodeproj/project.pbxproj
Labels: bug, high priority

#24 Fix - Last update date is off by an hour
  ViteMaDose/ViewModels/VaccinationCentres/VaccinationCentresViewModel.swift
Labels: bug, high priority

#26 ♻️ Rebuilding API service
  ViteMaDose.xcodeproj/project.pbxproj
  ViteMaDose.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ViteMaDose/Helpers/Extensions/UIViewController+ErrorDisplayable.swift
  ViteMaDose/Networking/APIEndpoint.swift
  ViteMaDose/Networking/APIService.swift
  ViteMaDose/Networking/RemoteConfig.swift
  ViteMaDose/ViewModels/Home/HomeViewModel.swift
  ViteMaDose/ViewModels/VaccinationCentres/VaccinationCentresViewModel.swift
Labels: enhancement

#31 Refactor - Vaccination centres list
  ViteMaDose.xcodeproj/project.pbxproj
  ViteMaDose/ViewModels/CentresList/CentresListViewModel.swift
  ViteMaDose/ViewModels/Home/HomeViewModel.swift
  ViteMaDose/ViewModels/VaccinationCentres/VaccinationCentresViewModel.swift
  ViteMaDose/Views/CentresList/Cells/CentreCell.swift
  ViteMaDose/Views/CentresList/Cells/CentreCell.xib
  ViteMaDose/Views/CentresList/Cells/CentresStatsCell.swift
  ViteMaDose/Views/CentresList/Cells/CentresStatsCell.xib
  ViteMaDose/Views/CentresList/Cells/CentresTitleCell.swift
  ViteMaDose/Views/CentresList/Cells/CentresTitleCell.xib
  ViteMaDose/Views/CentresList/CentresListViewController.storyboard
  ViteMaDose/Views/CentresList/CentresListViewController.swift
  ViteMaDose/Views/CountySelection/Header/CountySelectionHeaderView.swift
  ViteMaDose/Views/Home/Cells/HomeCountyCell.swift
  ViteMaDose/Views/Home/Cells/HomeCountySelectionCell.swift
  ViteMaDose/Views/Home/Cells/HomeStatsCell.swift
  ViteMaDose/Views/Home/Cells/HomeTitleCell.swift
  ViteMaDose/Views/Home/HomeViewController.swift
  ViteMaDose/Views/VaccinationCentres/Header/VaccinationCentresHeaderView.swift
  ViteMaDose/Views/VaccinationCentres/Header/VaccinationCentresHeaderView.xib
  ViteMaDose/Views/VaccinationCentres/VaccinationCentresViewController.swift
Labels: enhancement, refactoring

#36 Fix - Crash when tapping on an address on iPad
  ViteMaDose/Views/CentresList/Cells/CentreCell.swift
  ViteMaDose/Views/CentresList/CentresListViewController.swift
Labels: bug, high priority

#39 Fixed auto build number and version script
  Scripts/set_build_number.sh
  ViteMaDose.xcodeproj/project.pbxproj
  ViteMaDose/Info.plist
Labels: bug, high priority

#44 Because a great project needs a great README
  README.md
Labels: documentation

#63 Integrate swift lint + fix warnings
  .swiftlint.yml
  ViteMaDose.xcodeproj/project.pbxproj
  ViteMaDose/Helpers/Extensions/StringExtension.swift
  ViteMaDose/Helpers/Extensions/UITableView+Commons.swift
  ViteMaDose/Helpers/Extensions/UIViewControllerController+Commons.swift
  ViteMaDose/Helpers/Extensions/URL+Commons.swift
  ViteMaDose/Helpers/Utils/AppAnalytics.swift
  ViteMaDose/Models/County.swift
  ViteMaDose/Models/PartnerLogo.swift
  ViteMaDose/Models/Stats.swift
  ViteMaDose/Models/VaccinationCentre.swift
  ViteMaDose/Networking/APIService.swift
  ViteMaDose/Networking/RemoteConfig.swift
  ViteMaDose/SceneDelegate.swift
  ViteMaDose/ViewModels/CentresList/CentresListViewModel.swift
  ViteMaDose/Views/CentresList/Cells/CentreCell.swift
  ViteMaDose/Views/CentresList/Cells/CentreCell.xib
  ViteMaDose/Views/CentresList/Cells/CentresTitleCell.swift
  ViteMaDose/Views/CentresList/CentresListViewController.swift
  ViteMaDose/Views/CountySelection/CountySelectionViewController.swift
  ViteMaDose/Views/CountySelection/Header/CountySelectionHeaderView.swift
  ViteMaDose/Views/Home/Cells/HomeCountySelectionCell.swift
  ViteMaDose/Views/Home/Cells/HomeStatsCell.swift
  ViteMaDose/Views/Home/Cells/HomeTitleCell.swift
  ViteMaDose/Views/Home/Footer/HomePartnersFooterView.swift
  ViteMaDose/Views/Home/HomeViewController.swift
Labels: enhancement

#68 Fix - Mapharma date parsing
  ViteMaDose.xcodeproj/project.pbxproj
  ViteMaDose/Helpers/Extensions/String+DateParsing.swift
  ViteMaDose/ViewModels/CentresList/CentresListViewModel.swift
Labels: bug, high priority

#72 🔧 Check total is not zero
  ViteMaDose/Models/Stats.swift
  ViteMaDose/Views/Home/Cells/HomeStatsCell.swift
Labels: bug

#73 Feature - Localization
  ViteMaDose.xcodeproj/project.pbxproj
  ViteMaDose/Helpers/Extensions/String+Commons.swift
  ViteMaDose/Helpers/Extensions/StringExtension.swift
  ViteMaDose/Helpers/Extensions/UIViewController+ErrorDisplayable.swift
  ViteMaDose/Helpers/Utils/FormatterUtils.swift
  ViteMaDose/Models/Stats.swift
  ViteMaDose/Networking/APIService.swift
  ViteMaDose/Resources/Localization/Localization.swift
  ViteMaDose/Resources/Localization/fr.lproj/Localizable.strings
  ViteMaDose/Resources/Localization/fr.lproj/Localizable.stringsdict
  ViteMaDose/ViewModels/CentresList/CentresListViewModel.swift
  ViteMaDose/ViewModels/Home/HomeViewModel.swift
  ViteMaDose/Views/CentresList/Cells/CentreCell.swift
  ViteMaDose/Views/CentresList/Cells/CentreCell.xib
  ViteMaDose/Views/CentresList/Cells/CentresStatsCell.swift
  ViteMaDose/Views/CentresList/Cells/CentresStatsCell.xib
  ViteMaDose/Views/CentresList/Cells/CentresTitleCell.swift
  ViteMaDose/Views/CountySelection/Cells/CountyCell.swift
  ViteMaDose/Views/CountySelection/Header/CountySelectionHeaderView.swift
  ViteMaDose/Views/Home/Cells/HomeCountySelectionCell.swift
  ViteMaDose/Views/Home/Cells/HomeStatsCell.swift
  ViteMaDose/Views/Home/Cells/HomeTitleCell.swift
  ViteMaDose/Views/Home/Footer/HomePartnersFooterView.swift
Labels: enhancement

#74 Fix - Reload stats crash on Home
  ViteMaDose/ViewModels/Home/HomeViewModel.swift
  ViteMaDose/Views/Home/HomeViewController.swift
Labels: bug

#80 Firebase - Distinct debug project
  Scripts/firebase-spm.sh
  Scripts/set-google-plist.sh
  ViteMaDose.xcodeproj/project.pbxproj
  ViteMaDose.xcodeproj/xcshareddata/xcschemes/Debug.xcscheme
  ViteMaDose/GoogleService-Info-debug.plist
  ViteMaDose/GoogleService-Info-prod.plist
  ViteMaDose/Resources/Assets.xcassets/AppIconDebug.appiconset/Contents.json
  ViteMaDose/Resources/Assets.xcassets/AppIconDebug.appiconset/icon-debug-1024.png
  ViteMaDose/Resources/Assets.xcassets/AppIconDebug.appiconset/icon-debug-20.png
  ViteMaDose/Resources/Assets.xcassets/AppIconDebug.appiconset/icon-debug-20@2x.png
  ViteMaDose/Resources/Assets.xcassets/AppIconDebug.appiconset/icon-debug-20@3x.png
  ViteMaDose/Resources/Assets.xcassets/AppIconDebug.appiconset/icon-debug-29.png
  ViteMaDose/Resources/Assets.xcassets/AppIconDebug.appiconset/icon-debug-29@2x.png
  ViteMaDose/Resources/Assets.xcassets/AppIconDebug.appiconset/icon-debug-29@3x.png
  ViteMaDose/Resources/Assets.xcassets/AppIconDebug.appiconset/icon-debug-40.png
  ViteMaDose/Resources/Assets.xcassets/AppIconDebug.appiconset/icon-debug-40@2x.png
  ViteMaDose/Resources/Assets.xcassets/AppIconDebug.appiconset/icon-debug-40@3x.png
  ViteMaDose/Resources/Assets.xcassets/AppIconDebug.appiconset/icon-debug-60@2x.png
  ViteMaDose/Resources/Assets.xcassets/AppIconDebug.appiconset/icon-debug-60@3x.png
  ViteMaDose/Resources/Assets.xcassets/AppIconDebug.appiconset/icon-debug-76.png
  ViteMaDose/Resources/Assets.xcassets/AppIconDebug.appiconset/icon-debug-76@2x.png
  ViteMaDose/Resources/Assets.xcassets/AppIconDebug.appiconset/icon-debug-83.5@2x.png
Labels: enhancement, high priority

#82 Feature - Maintenance mode
  ViteMaDose.xcodeproj/project.pbxproj
  ViteMaDose/Networking/RemoteConfig.swift
  ViteMaDose/Resources/maintenance.html
  ViteMaDose/Views/Home/HomeViewController.swift
  ViteMaDose/Views/Maintenance/MaintenanceViewController.swift
  ViteMaDose/remote-configuration.plist
Labels: enhancement

#77 Tests - HomeViewModel
  ViteMaDose.xcodeproj/project.pbxproj
  ViteMaDose.xcodeproj/xcshareddata/xcschemes/ViteMaDoseTests.xcscheme
  ViteMaDose/AppDelegate.swift
  ViteMaDose/Helpers/Utils/UserDefaultsUtils.swift
  ViteMaDose/Helpers/Utils/UserDefaultsWrapper.swift
  ViteMaDose/Models/County.swift
  ViteMaDose/Models/PartnerLogo.swift
  ViteMaDose/Models/Stats.swift
  ViteMaDose/Models/VaccinationCentre.swift
  ViteMaDose/Networking/APIService.swift
  ViteMaDose/ViewModels/CentresList/CentresListViewModel.swift
  ViteMaDose/ViewModels/CountySelection/CountySelectionViewModel.swift
  ViteMaDose/ViewModels/Home/HomeViewModel.swift
  ViteMaDose/Views/Home/Cells/HomeStatsCell.swift
  ViteMaDoseTests/Networking/APIServiceMock.swift
  ViteMaDoseTests/ViewModels/Home/HomeViewModelDelegateSpy.swift
  ViteMaDoseTests/ViewModels/Home/HomeViewModelTests.swift
  ViteMaDoseTests/ViteMaDoseTests-Bridging-Header.h
  ViteMaDoseTests/ViteMaDoseTests.swift
  ViteMaDoseUITests/Info.plist
  ViteMaDoseUITests/ViteMaDoseUITests.swift
Labels: unit-tests
