Repository CovidTrackerFr/vitemadose-ios, pull requests merged in 2021-05, with the labels that each got.

#90 Feature - Rewrite networking
  ViteMaDose.xcodeproj/project.pbxproj
  ViteMaDose.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ViteMaDose/Helpers/Extensions/UIViewController+ErrorDisplayable.swift
  ViteMaDose/Helpers/Extensions/URL+Commons.swift
  ViteMaDose/Models/City.swift
  ViteMaDose/Networking/APIService.swift
  ViteMaDose/Networking/BaseAPIService.swift
  ViteMaDose/Networking/CachePolicyPlugin.swift
  ViteMaDose/Networking/GeoAPIService.swift
  ViteMaDose/Networking/RemoteConfig.swift
  ViteMaDose/ViewModels/CentresList/CentresListViewModel.swift
  ViteMaDose/ViewModels/CountySelection/CountySelectionViewModel.swift
  ViteMaDose/ViewModels/Home/HomeViewModel.swift
  ViteMaDoseTests/Networking/APIServiceMock.swift
  ViteMaDoseTests/Networking/BaseAPIServiceMock.swift
  ViteMaDoseTests/ViewModels/Home/HomeViewModelTests.swift
Labels: refactoring

#91 Refactor - Rename county with department
  ViteMaDose.xcodeproj/project.pbxproj
  ViteMaDose/Helpers/Utils/AppAnalytics.swift
  ViteMaDose/Helpers/Utils/UserDefaultsUtils.swift
  ViteMaDose/Models/Department.swift
  ViteMaDose/Models/Stats.swift
  ViteMaDose/Networking/BaseAPIService.swift
  ViteMaDose/Resources/Localization/Localization.swift
  ViteMaDose/Resources/Localization/fr.lproj/Localizable.strings
  ViteMaDose/ViewModels/CentresList/CentresListViewModel.swift
  ViteMaDose/ViewModels/CountySelection/CountySelectionViewModel.swift
  ViteMaDose/ViewModels/DepartmentSelection/DepartmentSelectionViewModel.swift
  ViteMaDose/ViewModels/Home/HomeViewModel.swift
  ViteMaDose/Views/CentresList/Cells/CentresTitleCell.swift
  ViteMaDose/Views/CountySelection/Cells/CountyCell.swift
  ViteMaDose/Views/DepartmentSelection/Cells/DepartmentCell.swift
  ViteMaDose/Views/DepartmentSelection/Cells/DepartmentCell.xib
  ViteMaDose/Views/DepartmentSelection/DepartmentSelectionViewController.storyboard
  ViteMaDose/Views/DepartmentSelection/DepartmentSelectionViewController.swift
  ViteMaDose/Views/DepartmentSelection/Header/DepartmentSelectionHeaderView.swift
  ViteMaDose/Views/DepartmentSelection/Header/DepartmentSelectionHeaderView.xib
  ViteMaDose/Views/Home/Cells/HomeDepartmentCell.swift
  ViteMaDose/Views/Home/Cells/HomeDepartmentCell.xib
  ViteMaDose/Views/Home/Cells/HomeDepartmentSelectionCell.swift
  ViteMaDose/Views/Home/Cells/HomeDepartmentSelectionCell.xib
  ViteMaDose/Views/Home/HomeViewController.swift
  ViteMaDoseTests/Networking/BaseAPIServiceMock.swift
  ViteMaDoseTests/ViewModels/Home/HomeViewModelDelegateSpy.swift
  ViteMaDoseTests/ViewModels/Home/HomeViewModelTests.swift
Labels: refactoring

#93 Feature - Sort options
  ViteMaDose.xcodeproj/project.pbxproj
  ViteMaDose/Helpers/Utils/UserDefaultsUtils.swift
  ViteMaDose/Models/LocationSearchResult.swift
  ViteMaDose/Models/VaccinationCentre.swift
  ViteMaDose/Resources/Localization/Localization.swift
  ViteMaDose/Resources/Localization/fr.lproj/Localizable.strings
  ViteMaDose/ViewModels/CentresList/CentresListViewModel.swift
  ViteMaDose/Views/CentresList/Cells/CentresSortOptionsCell.swift
  ViteMaDose/Views/CentresList/Cells/CentresSortOptionsCell.xib
  ViteMaDose/Views/CentresList/CentresListViewController.swift
Labels: enhancement

#96 ✨ Added analytics for centres list
  ViteMaDose/Helpers/Utils/AppAnalytics.swift
  ViteMaDose/ViewModels/CentresList/CentresListViewModel.swift
Labels: analytics, high priority

#95 🐛 Fixed an issue where recent searches were not always uniqued
  ViteMaDose/Helpers/Utils/UserDefaultsUtils.swift
Labels: high priority

#118 Fixes - Fixed home crash and added small improvements
  .swiftlint.yml
  ViteMaDose/Helpers/Extensions/Array+Commons.swift
  ViteMaDose/Helpers/Utils/OnboardingManager.swift
  ViteMaDose/Models/VaccinationCentre.swift
  ViteMaDose/Resources/Localization/Localization.swift
  ViteMaDose/Resources/Localization/fr.lproj/Localizable.strings
  ViteMaDose/ViewModels/CentresList/CentresListViewModel.swift
  ViteMaDose/Views/CentresList/Cells/CentreCell.swift
  ViteMaDose/Views/CentresList/Cells/CentreCell.xib
  ViteMaDose/Views/Home/HomeViewController.swift
Labels: bug, enhancement

#116 ✨ Display Chronodose number & accuracy improvement
  ViteMaDose/Models/VaccinationCentre.swift
  ViteMaDose/Networking/RemoteConfig.swift
  ViteMaDose/ViewModels/CentresList/CentresListViewModel.swift
  ViteMaDose/Views/CentresList/Cells/CentreCell.swift
  ViteMaDose/remote-configuration.plist
Labels: enhancement

#119 Feature - Open URL from push
  ViteMaDose/AppDelegate.swift
Labels: enhancement
