Repository CovidTrackerFr/vitemadose-ios, pull requests merged in 2022-01, with the labels that each got.

#134 Forge string dedicated to accessibility label to improve vocalization of big numbers containing whitespaces
  ViteMaDose/Helpers/Extensions/String+Commons.swift
  ViteMaDose/Views/Home/Cells/HomeTitleCell.swift
Labels: bug, UI

#169 Update icons for settings and onboarding
  ViteMaDose/Helpers/Utils/OnboardingManager.swift
  ViteMaDose/Resources/Localization/Localization.swift
  ViteMaDose/Resources/Localization/fr.lproj/Localizable.strings
  ViteMaDose/Views/Home/HomeViewController.storyboard
  ViteMaDose/Views/Settings/Cells/SettingsCell.swift
Labels: bug, enhancement, UI

#170 [Refactoring] [#167] Remove items relatetd to chronodoses
  ViteMaDose/Helpers/Utils/FCMHelper.swift
  ViteMaDose/Models/FollowedCentre.swift
  ViteMaDose/Models/VaccinationCentre.swift
  ViteMaDose/Networking/RemoteConfig.swift
  ViteMaDose/Resources/Localization/fr.lproj/Localizable.strings
  ViteMaDose/ViewModels/CentresList/CentresListViewModel.swift
  ViteMaDose/Views/CentresList/Cells/CentreCell.swift
  ViteMaDose/Views/CentresList/Cells/CentreCell.xib
  ViteMaDose/Views/CentresList/CentresListViewController.swift
  ViteMaDose/remote-configuration.plist
Labels: refactoring

#171 [Feature] [#144] Display type of vaccination center
  ViteMaDose/Helpers/Utils/AppAnalytics.swift
  ViteMaDose/Models/VaccinationCentre.swift
  ViteMaDose/Resources/Localization/Localization.swift
  ViteMaDose/Resources/Localization/fr.lproj/Localizable.strings
  ViteMaDose/ViewModels/CentresList/CentresListViewModel.swift
  ViteMaDose/Views/CentresList/Cells/CentreCell.swift
  ViteMaDose/Views/CentresList/Cells/CentreCell.xib
Labels: enhancement, UI

#174 [#148] Location slider for maximal radius
  ViteMaDose/Helpers/Utils/UserDefaultsUtils.swift
  ViteMaDose/Networking/RemoteConfig.swift
  ViteMaDose/Resources/Localization/fr.lproj/Localizable.strings
  ViteMaDose/Settings.bundle/Root.plist
Labels: enhancement, UI, high priority

#163 [Feature] [#162] [#154] Filtering of centres by kids first doses and vaccine types
  ViteMaDose.xcodeproj/project.pbxproj
  ViteMaDose/Helpers/Classes/AccessibilityString.swift
  ViteMaDose/Helpers/Extensions/UIColor+ViteMaDose.swift
  ViteMaDose/Helpers/Extensions/UIDevice+common.swift
  ViteMaDose/Helpers/Extensions/URL+Commons.swift
  ViteMaDose/Helpers/Utils/AppAnalytics.swift
  ViteMaDose/Helpers/Utils/OnboardingManager.swift
  ViteMaDose/Helpers/Utils/UserDefaultsUtils.swift
  ViteMaDose/Models/DailySlot.swift
  ViteMaDose/Models/VaccinationCentre.swift
  ViteMaDose/Models/VaccineType.swift
  ViteMaDose/Resources/Localization/Localization.swift
  ViteMaDose/Resources/Localization/fr.lproj/Localizable.strings
  ViteMaDose/ViewModels/CentresList/CentresListFilterOption.swift
  ViteMaDose/ViewModels/CentresList/CentresListSortOption.swift
  ViteMaDose/ViewModels/CentresList/CentresListViewModel.swift
  ViteMaDose/ViewModels/CentresList/CentresListViewModelProvider.swift
  ViteMaDose/ViewModels/Credit/CreditViewModel.swift
  ViteMaDose/Views/CentresList/Cells/CentreActionCell.swift
  ViteMaDose/Views/CentresList/Cells/CentreActionCell.xib
  ViteMaDose/Views/CentresList/Cells/CentreCell.swift
  ViteMaDose/Views/CentresList/Cells/CentresSortOptionsCell.swift
  ViteMaDose/Views/CentresList/CentresListViewController.storyboard
  ViteMaDose/Views/CentresList/CentresListViewController.swift
  ViteMaDose/Views/Credits/Cells/CreditCell.swift
  ViteMaDose/Views/Settings/SettingsViewController.swift
Labels: enhancement, UI, high priority

#178 Fix release building issues & warnings
  ViteMaDose.xcodeproj/project.pbxproj
  ViteMaDose.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ViteMaDose/Helpers/Extensions/UIDevice+common.swift
  ViteMaDose/Models/Credit.swift
  ViteMaDose/ViewModels/Credit/CreditViewModel.swift
  ViteMaDose/Views/CentresList/Cells/CentreActionCell.swift
  ViteMaDose/Views/CentresList/Cells/CentreActionCell.xib
  ViteMaDose/Views/Credits/Cells/CreditCell.swift
  ViteMaDose/Views/Credits/Cells/CreditCell.xib
  ViteMaDose/Views/Home/HomeViewController.storyboard
  ViteMaDose/Views/Home/HomeViewController.swift
  ViteMaDose/Views/Settings/Cells/SettingsCell.xib
Labels: bug, high priority
